spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/audit
    username: postgres
    password: 13245
    hikari:
      maximum-pool-size: 15

server:
  port: 8093