spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://pg_db:5432/classifier?currentSchema=classifier_data
    username: calssifier_app_user
    password: 13245
    hikari:
      maximum-pool-size: 15

client:
  account-service:
    url: http://account-service:8080