spring:
  application:
    name: classifier-service
  jpa:
    properties:
      hibernate:
        show_sql: true
  task:
    execution:
      pool:
        core-pool-size: 5
        max-pool-size: 10
        queue-capacity: 20
      shutdown:
        await-termination: true
        await-termination-period: 45

app:
  jwt:
    secret: NmIxNTkwNWUtYWQwZS00ZGM4LWE4MzctZjdlNDQ4ZTllMDlh
    issuer: ITAcademy

