spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://pg_db:5432/users?currentSchema=user_data
    username: user_app_user
    password: 13245
    hikari:
      maximum-pool-size: 15

verification:
  url: http://localhost/api/v1/cabinet/verification
  subject: Верификация пользователя PersonalFinance