spring:
  application:
   name: user-service
  jpa:
    properties:
      hibernate:
        show_sql: true
  mail:
    host: smtp.yandex.ru
    port: 465
    username: javatest333@yandex.by
    password: ifxuokbybugqevmr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
  task:
    execution:
      pool:
        core-pool-size: 5
        max-pool-size: 10
        queue-capacity: 20
      shutdown:
        await-termination: true
        await-termination-period: 45

app:
  jwt:
    secret: NmIxNTkwNWUtYWQwZS00ZGM4LWE4MzctZjdlNDQ4ZTllMDlh
    issuer: ITAcademy





